apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: operators
spec:
  project: default

  source:
    repoURL: https://github.com/110melanin/ArgoCD-pipeline-manifests.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: operators

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
